openapi: 3.0.0
info:
  title: Pepecoin Payment Gateway API
  version: "1.0.0"
  description: >
    An API for processing Pepecoin payments, including order creation, payment monitoring, and status retrieval.

servers:
  - url: https://api.pepecoinpaymentgateway.com/v1
    description: Production server
  - url: https://sandbox.api.pepecoinpaymentgateway.com/v1
    description: Sandbox server for testing

paths:
  /orders:
    post:
      summary: Create a new order
      operationId: createOrder
      tags:
        - Orders
      requestBody:
        description: Order creation payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Order successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: List all orders
      operationId: listOrders
      tags:
        - Orders
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [Pending, Paid, Expired, Cancelled]
          description: Filter orders by status
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
          description: Number of orders to return
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          description: Pagination offset
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrdersListResponse'

  /orders/{order_id}:
    get:
      summary: Retrieve order details
      operationId: getOrder
      tags:
        - Orders
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
          description: Unique identifier for the order
      responses:
        '200':
          description: Order details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Cancel an order
      operationId: cancelOrder
      tags:
        - Orders
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
          description: Unique identifier for the order
      responses:
        '200':
          description: Order successfully cancelled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    OrderRequest:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: float
          description: Amount to be paid in Pepecoin
          example: 10.5
        currency:
          type: string
          description: Currency code (e.g., PEPE, USD)
          example: PEPE
        description:
          type: string
          description: Description of the order
          example: "Purchase of digital artwork"
        customer_email:
          type: string
          format: email
          description: Customer's email address
          example: "customer@example.com"
        order_metadata:
          type: object
          description: Additional data for the order
          additionalProperties:
            type: string

    OrderResponse:
      type: object
      properties:
        order_id:
          type: string
          description: Unique identifier for the order
          example: "ord_123456789"
        payment_address:
          type: string
          description: Unique Pepecoin address for this order
          example: "PpK1q2w3e4r5t6y7u8i9o0pLkJhGfDsA"
        amount_due:
          type: number
          format: float
          description: Amount due in Pepecoin
          example: 10.5
        amount_paid:
          type: number
          format: float
          description: Amount paid by the customer
          example: 10.5
        status:
          type: string
          description: Current status of the order
          enum: [Pending, Paid, Underpaid, Overpaid, Expired, Cancelled]
          example: "Paid"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the order was created
          example: "2023-10-15T12:34:56Z"
        expires_at:
          type: string
          format: date-time
          description: Timestamp when the order expires
          example: "2023-10-15T13:34:56Z"
        transactions:
          type: array
          description: List of transactions associated with the order
          items:
            $ref: '#/components/schemas/Transaction'
        order_metadata:
          type: object
          description: Additional data associated with the order
          additionalProperties:
            type: string

    Transaction:
      type: object
      properties:
        txid:
          type: string
          description: Transaction ID on the Pepecoin blockchain
          example: "b6f6991d3c...e8e8e8e8e8"
        amount:
          type: number
          format: float
          description: Amount transferred in the transaction
          example: 10.5
        confirmations:
          type: integer
          description: Number of confirmations the transaction has received
          example: 3
        timestamp:
          type: string
          format: date-time
          description: Time when the transaction was detected
          example: "2023-10-15T12:35:00Z"

    OrdersListResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderResponse'
        total_count:
          type: integer
          description: Total number of orders available
          example: 100

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Order not found"
        code:
          type: integer
          description: Error code
          example: 404

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

tags:
  - name: Orders
    description: Endpoints related to order management


