# coding: utf-8

"""
    Pepecoin Payment Gateway API

    An API for processing Pepecoin payments, including order creation, payment monitoring, and status retrieval. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class OrderRequest(BaseModel):
    """
    OrderRequest
    """ # noqa: E501
    amount: Union[StrictFloat, StrictInt] = Field(description="Amount to be paid in Pepecoin")
    currency: Optional[StrictStr] = Field(default=None, description="Currency code (e.g., PEPE, USD)")
    description: Optional[StrictStr] = Field(default=None, description="Description of the order")
    customer_email: Optional[StrictStr] = Field(default=None, description="Customer's email address")
    order_metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional data for the order")
    __properties: ClassVar[List[str]] = ["amount", "currency", "description", "customer_email", "order_metadata"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "description": obj.get("description"),
            "customer_email": obj.get("customer_email"),
            "order_metadata": obj.get("order_metadata")
        })
        return _obj


